-- MySQL Script generated by MySQL Workbench
-- 08/21/18 18:02:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`avaliador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliador` (
  `id_avaliador` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `usuario` VARCHAR(45) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_avaliador`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atividade` (
  `id_atividade` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `descricao` VARCHAR(45) NOT NULL COMMENT '',
  `dificuldade` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_atividade`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `id_sala` INT NOT NULL COMMENT '',
  `pin` VARCHAR(45) NOT NULL COMMENT '',
  `avaliador_id_avaliador` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_sala`, `avaliador_id_avaliador`)  COMMENT '',
  INDEX `fk_sala_avaliador1_idx` (`avaliador_id_avaliador` ASC)  COMMENT '',
  CONSTRAINT `fk_sala_avaliador1`
    FOREIGN KEY (`avaliador_id_avaliador`)
    REFERENCES `mydb`.`avaliador` (`id_avaliador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atividade_has_avaliador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atividade_has_avaliador` (
  `atividade_id_atividade` INT NOT NULL COMMENT '',
  `avaliador_id_avaliador` INT NOT NULL COMMENT '',
  PRIMARY KEY (`atividade_id_atividade`, `avaliador_id_avaliador`)  COMMENT '',
  INDEX `fk_atividade_has_avaliador_avaliador1_idx` (`avaliador_id_avaliador` ASC)  COMMENT '',
  INDEX `fk_atividade_has_avaliador_atividade1_idx` (`atividade_id_atividade` ASC)  COMMENT '',
  CONSTRAINT `fk_atividade_has_avaliador_atividade1`
    FOREIGN KEY (`atividade_id_atividade`)
    REFERENCES `mydb`.`atividade` (`id_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividade_has_avaliador_avaliador1`
    FOREIGN KEY (`avaliador_id_avaliador`)
    REFERENCES `mydb`.`avaliador` (`id_avaliador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
